[tool.poetry]
name = "de-zoomcamp-25"
version = "0.1.0"
description = ""
authors = ["Camilo Perez <camilo.perez@midiagnostics.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
